# Generated by Django 4.0 on 2022-01-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Brands')),
            ],
            options={
                'verbose_name': 'Available Brand',
                'verbose_name_plural': 'Available Brands',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('button_link', models.URLField()),
                ('image', models.ImageField(upload_to='Banners')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=500)),
                ('image', models.ImageField(upload_to='Spotlight')),
            ],
            options={
                'verbose_name': 'Spotlight',
                'verbose_name_plural': 'Spotlight',
            },
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=150)),
                ('buttonLink', models.URLField()),
                ('image', models.ImageField(upload_to='Featured Collections')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=250)),
                ('collection', models.ManyToManyField(to='CMS.FeaturedCollection')),
            ],
            options={
                'verbose_name': 'Featured Collection',
                'verbose_name_plural': 'Featured Collections',
            },
        ),
    ]
