# Generated by Django 4.0 on 2021-12-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_best_selling_product_featured_and_more'),
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcollection',
            name='category',
        ),
        migrations.AddField(
            model_name='featuredcollection',
            name='category',
            field=models.ManyToManyField(to='Products.Category'),
        ),
    ]
