# Generated by Django 4.0 on 2021-12-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_best_selling_product_featured_and_more'),
        ('CMS', '0002_remove_featuredcollection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='collection',
        ),
        migrations.AddField(
            model_name='featured',
            name='collection',
            field=models.ManyToManyField(to='CMS.FeaturedCollection'),
        ),
        migrations.RemoveField(
            model_name='featuredcollection',
            name='category',
        ),
        migrations.AddField(
            model_name='featuredcollection',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
            preserve_default=False,
        ),
    ]
