# Generated by Django 4.0 on 2022-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_rename_sectiondescription_featured_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=500)),
                ('image', models.ImageField(upload_to='Spotlight')),
            ],
            options={
                'verbose_name': 'Spotlight',
                'verbose_name_plural': 'Spotlight',
            },
        ),
    ]
