# Generated by Django 4.0 on 2022-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.JSONField(max_length=5000)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_id'],
            },
        ),
    ]
