# Generated by Django 4.0 on 2022-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(max_length=5000)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.PositiveIntegerField(max_length=10)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
    ]
