# Generated by Django 4.0 on 2022-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_order_options_remove_order_id_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(max_length=5000),
        ),
    ]
