# Generated by Django 4.0 on 2022-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_stock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, through='Products.stock', to='Products.size'),
        ),
    ]
